version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: app-backend-prod
    container_name: app-node-backend-prod
    environment:
      - NODE_ENV=production
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: app-frontend-prod
    container_name: app-node-frontend-prod
    environment:
      - NODE_ENV=production
    env_file: ./frontend/.env
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
