services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: app-backend
    container_name: app-node-backend
    command: /src/app/node_modules/.bin/nodemon /src/app/server.js
    volumes:
      - ./backend/:/src/app
      - /src/app/node_modules
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: app-frontend
    container_name: app-node-frontend
    command: npm run dev
    volumes:
      - ./frontend/:/src/app
      - /src/app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
