# docker file for backend

FROM node:18-alpine

# Install necessary dependencies for Puppeteer
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    nodejs \
    yarn

ENV PORT=8000
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

RUN mkdir -p  /src/app
WORKDIR /src/app

COPY package*.json ./
RUN npm install

COPY . .


EXPOSE 8000

CMD ["npm", "start"]
